### ISSUE TITLE
Support for secure connection wss://

### ISSUE THREAD

**Issue by bridger** [IBM-Swift/Kitura-WebSocket-NIO#14]
[Kitura-NIO has a "todo" to support the wss upgrade](https://github.com/IBM-Swift/Kitura-NIO/blob/a20358f440d0eba49326f3306711450a9b78d4cc/Sources/KituraNet/HTTP/HTTPServer.swift#L190). Does this mean secure websocket connections are not yet supported in this version of Kitura-Websocket?

**Comment by pushkarnk** [comment]
Presuming that a Kitura server, on which a WebSocket upgrade is requested for, has a configured SSLContext, we need to make sure that the subsequently configured `NIOSSLServerHandler`, which is the first `InboundHandler` and the last `OutboundHandler` is retained in the same position after a successful WebSocket upgrade. But I wonder how we are going to differentiate between a `ws` request and a `wss` request that are received on an HTTP server configured with SSL/TLS. Possibly [here](https://github.com/IBM-Swift/Kitura-NIO/blob/master/Sources/KituraNet/HTTP/HTTPServer.swift#L188).

**Comment by pushkarnk** [comment]
OK, I figured out that we DO support WSS. 

I set up a simple WebSocket echo service with a Kitura server like this:
```
let sslConfig: SSLConfig = {
    let sslConfigDir = URL(fileURLWithPath: #file).deletingLastPathComponent().appendingPathComponent("../SSLConfig")
    let chainFilePath = sslConfigDir.appendingPathComponent("certificateChain.pfx").standardized.path
    return SSLConfig(withChainFilePath: chainFilePath, withPassword: "kitura",
                     usingSelfSignedCerts: true)
}()

// Using an implementation for a Logger
HeliumLogger.use(.info)
let router = Router()
WebSocket.register(service: EchoService(), onPath: "/")
let port = 9001
Kitura.addHTTPServer(onPort: port, with: router, withSSL: sslConfig)
Kitura.run()
```

I then accessed the HTTPS URL: `https://localhost:9001/` and added the certificate as prompted by the browser. After that I was able to make a `wss` connection to this echo service using the Simple WebSocket Client extension on Firefox/Chrome.

**Comment by pushkarnk** [comment]
I have changed all our client-server tests to use secure web socket connections: https://github.com/IBM-Swift/Kitura-WebSocket-NIO/pull/19

**Comment by bridger** [comment]
Thank you for checking that it is supported!

**Comment by bridger** [comment]
Maybe the TODO should be removed from the code?
