### ISSUE TITLE
Unable to connect with Chrome / Firefox

### ISSUE THREAD

**Issue by bridger** [IBM-Swift/Kitura-WebSocket-NIO#15]
I'm trying to connect to my Kitura websocket server using Chrome or Firefox. Both receive an error 400 response.

I see this error in the upgrader is being thrown:

            guard let extraHeaders = extraHeaders else {
                throw NIOWebSocketUpgradeError.unsupportedWebSocketTarget
            }

I'm not sure why the error means.

Here is the Typescript / Javascript code which tries to make the websocket connection:

```
      let ws = this.ws = new WebSocket(websocketURL);
      ws.binaryType = 'arraybuffer';
      ws.onopen = (event) => {
        console.log("Websocket opened");
      };
      ws.onmessage = this.onWebsocketRawMessage;
      ws.onclose = (event) => {
        console.log("Websocket closed");
        this.closeAndRetryWebsocketConnectionAfterDelay()
      };
```

Instead of headers (which are unsupported by the Javascript websocket API) I use URL parameters. That means websocketURL looks something like this:
`ws://Dr-Octavius.local:9080/api/canvas/ws?SCRBL-Access-Level=READ&SCRBL-Client-Type=WEB&SCRBL-Device-Id=347&SCRBL-Document-Id=C0C0AC2D-5DC9-4F35-836A-ADC81931F8C8&SCRBL-Timestamp=2019-04-28T16%3A38%3A38Z&SCRBL-User-Id=23`

**Comment by pushkarnk** [comment]
One reason for the upgrader refusing an upgrade could be: If the WebSocket service is registered at `/ws` and the request uri is `/ws?param=1` the upgrader is going to check if a service is registered at `/ws?param=1` and hence refuse the upgrade. 

Clearly, the reason for this is that we haven't considered URL parameters!

**Comment by pushkarnk** [comment]
In a URL like
```
ws://Dr-Octavius.local:9080/api/canvas/ws?SCRBL-Access-Level=READ&SCRBL-Client-Type=WEB&SCRBL-Device-Id=347&SCRBL-Document-Id=C0C0AC2D-5DC9-4F35-836A-ADC81931F8C8&SCRBL-Timestamp=2019-04-28T16%3A38%3A38Z&SCRBL-User-Id=23
```
... if all of those query parameters are to be supplied to the WebSocket service, I wonder how we are going to pass them to the service 🤔

**Comment by bridger** [comment]
This worked in Kitura Websockets before NIO. I was able to get the URL parameters in the Websocket service like this:

    let parsedURL = URLParser(url: connection.request.url, isConnect: false)
    var requestParams = parsedURL.queryParameters.mapValues({ $0.removingPercentEncoding ?? $0 })

**Comment by pushkarnk** [comment]
> This worked in Kitura Websockets before NIO. I was able to get the URL parameters in the Websocket service like this:
> 
> ```
> let parsedURL = URLParser(url: connection.request.url, isConnect: false)
> var requestParams = parsedURL.queryParameters.mapValues({ $0.removingPercentEncoding ?? $0 })
> ```

Thanks for this input. Then I guess, all we'd have to do in Kitura-WebSocket-NIO is make sure that we strip the query parameters from the URI while checking if a WebSocket service is registered there.

**Comment by pushkarnk** [comment]
Raised https://github.com/IBM-Swift/Kitura-NIO/pull/201 against `Kitura-NIO`. Once this is merged I'll add a test or two to `Kitura-WebSocket-NIO`.

**Comment by pushkarnk** [comment]
Added a test that exercises query params: https://github.com/IBM-Swift/Kitura-WebSocket-NIO/pull/20

**Comment by bridger** [comment]
I'm now able to connect to a websocket endpoint with query parameters. Thank you!
