### ISSUE TITLE
Kitura-WebSocket-NIO leaks memory

### ISSUE THREAD

**Issue by pushkarnk** [IBM-Swift/Kitura-WebSocket-NIO#32]
I launched TestWebSocketService and ran the entire autobahn test twice. Here's the memory consumption at three different instances:

In the beginning while the server is idle and only listening - 6Mb
After one full autobahn run, while the server is idle and only listening - 74Mb
After two full autobahn runs: 140Mb

**Comment by pushkarnk** [comment]
Found a retain cycle `WebSocketConnection <----> ChannelHandlerContext`. Removing this cycle by making the reference to `ChannelHandlerContext` weak solves the memory leak but all the compression tests that use fragmentation start failing. Investigating that failure now.

**Comment by pushkarnk** [comment]
I think I was using a stale copy of the code. The failure were related to #26. Now doing 3 back-to-back autobahn runs with the fix.

**Comment by pushkarnk** [comment]
One part of this memory leak is the `WebSocketConnection <----> ChannelHandlerContext` retain cycle. Another part, the more serious one, is a bug in #26 which ends up initialising a z_stream for every message (even when context takeover is configured, ideally it should've been initialised once per connection) but frees it only once (because context takeover is configured). Fixing this bug breaks the autobahn tests. We're unable to use context for compressing outgoing messages. I'm on this now.

**Comment by ianpartridge** [comment]
Thanks Pushkar, looks like you're making good progress.

**Comment by pushkarnk** [comment]
So, we were not able to use the compressor with compression context, across the connection because of the zlib header. Some background to this issue here:

zlib supports three kinds of compression formats: 
a. zlib, by default ([rfc1950](http://tools.ietf.org/html/rfc1950))
b. raw deflate ([rfc1951](http://tools.ietf.org/html/rfc1951))
c. gzip ([rfc1952](http://tools.ietf.org/html/rfc1952))

*WebSocket compression is expected to use raw deflate streams.*

During compression, the first step is to initialize the deflater using deflateInit() or deflateInit2(). These functions take a parameter called windowBits which specifies the LZ77 window size to be used by the deflater. The permissible ranges for this parameter are:
a. 8...15 for zlib
b. -8...-15 for raw deflate
c. > 15 for gzip

We wrongly configured the deflater with windowBits in the 8...15 range resulting into the deflater emitting out a zlib header before the compressed data. The zlib header is 0x78 0x9C.
We did cover up for this issue elsewhere,  by stripping off this zlib header from the deflater output.

Now, when we use context takeover, the same compressor is used across the lifetime of a WebSocket connection. This means the same deflater is used. This deflater, wrongly configured to output a zlib stream, emits the zlib header only on the first deflate operation. The subsequent operations do not emit this header. So, while intending to strip off the zlib header for subsequent deflate operations, we were actually ended up corrupting user data. Hence the failures in autobahn.

These problems didn't arise earlier because we were not actually using context takeover for the (server-deflate -> client-inflate) case. We did have context takeover working for the (client-deflate -> server-inflate) case, in which we did not have to deflate!

The right solution to this problem is using a negative windowBits value while initializing the deflater.

More details here: https://github.com/madler/zlib/issues/93

**Comment by pushkarnk** [comment]
With a fix for the issue discussed above, we still have autobahn tests 13.3.*, 13.5.* and 13.7.* failing. What's common between all of these tests is that the client advertises a server_max_window_bits value of 8. Though we accepted that value for the server-side deflater, we did not return it in the negotiation response. Consequently, the server's deflater used 8 windowBits but the client's inflater tried to use the default 15 windowBits.
This was not really an issue because server's context takeover was broken. We were re-initializing the deflater on every message.

With context takeover implemented for the (server-deflate -> client-inflate) case, these tests started failing. The solution to that is simple. We just had to add a "server_max_window_bits=8" to the negotiation response. This is to notify the client that the "server_max_window_bits" value that it proposed has been accepted, which is used by the client's inflater. 

There's a known, open issue with the windowBits value 8, for reasons beyond the scope here. The deflater in zlib works around this by setting windowBits to 9, whenever the requested value is 8. Such a hack may work in the case of zlib streams where the size of the LZ77 window is encoded along with compressed data. It is possible for the inflater to read this value and adjust it's window size. However, this is not possible with raw deflate streams.
So, zlib has been patched to return a failure if a window size of -8 were used. The failing function is deflateInit2().

To work around this zlib limitation, we need to make sure we don't entertain "server_max_window_bits=8". If this is received in a negotiation offer, we set the window size of the deflater to 9 and return "server_max_window_bits=9" in the negotiation response.

Details of the zlib limitation are here: https://github.com/madler/zlib/issues/171

**Comment by pushkarnk** [comment]
> One part of this memory leak is the `WebSocketConnection <----> ChannelHandlerContext` retain cycle. Another part, the more serious one, is a bug in #26 which ends up initialising a z_stream for every message (even when context takeover is configured, ideally it should've been initialised once per connection) but frees it only once (because context takeover is configured). Fixing this bug breaks the autobahn tests. We're unable to use context for compressing outgoing messages. I'm on this now.

The more serious memory leak issue is with context takeover, when we persist the z_streams created for the deflater and the inflater for the lifetime of a connection. They must be cleaned up while the connection is being closed.

**Comment by pushkarnk** [comment]
> So, we were not able to use the compressor with compression context, across the connection because of the zlib header. Some background to this issue here:
> 
> zlib supports three kinds of compression formats:
> 
> * zlib, by default ([rfc1950](http://tools.ietf.org/html/rfc1950))
> * raw deflate ([rfc1951](http://tools.ietf.org/html/rfc1951))
> * gzip ([rfc1952](http://tools.ietf.org/html/rfc1952))
> 
> _WebSocket compression is expected to use raw deflate streams._
> 
> During compression, the first step is to initialize the deflater using deflateInit() or deflateInit2(). These functions take a parameter called windowBits which specifies the LZ77 window size to be used by the deflater. The permissible ranges for this parameter are:
> 
> * 8...15 for zlib
> * -8...-15 for raw deflate
> * more than 15 for gzip
> 
> We wrongly configured the deflater with windowBits in the 8...15 range resulting into the deflater emitting out a zlib header before the compressed data. The zlib header is 0x78 0x9C.
> We did cover up for this issue elsewhere, by stripping off this zlib header from the deflater output.
> 
> Now, when we use context takeover, the same compressor is used across the lifetime of a WebSocket connection. This means the same deflater is used. This deflater, wrongly configured to output a zlib stream, emits the zlib header only on the first deflate operation. The subsequent operations do not emit this header. So, while intending to strip off the zlib header for subsequent deflate operations, we were actually ended up corrupting user data. Hence the failures in autobahn.
> 
> These problems didn't arise earlier because we were not actually using context takeover for the (server-deflate -> client-inflate) case. We did have context takeover working for the (client-deflate -> server-inflate) case, in which we did not have to deflate!
> 
> The right solution to this problem is using a negative windowBits value while initializing the deflater.
> 
> More details here: [madler/zlib#93](https://github.com/madler/zlib/issues/93)

Commit: https://github.com/IBM-Swift/Kitura-WebSocket-NIO/pull/26/commits/52614a23dbff37db18e2c0fb70e282921c0bb666

**Comment by pushkarnk** [comment]
> With a fix for the issue discussed above, we still have autobahn tests 13.3._, 13.5._ and 13.7.* failing. What's common between all of these tests is that the client advertises a server_max_window_bits value of 8. Though we accepted that value for the server-side deflater, we did not return it in the negotiation response. Consequently, the server's deflater used 8 windowBits but the client's inflater tried to use the default 15 windowBits. This was not really an issue because server's context takeover was broken. We were re-initializing the deflater on every message.
> 
> With context takeover implemented for the (server-deflate -> client-inflate) case, these tests started failing. The solution to that is simple. We just had to add a "server_max_window_bits=8" to the negotiation response. This is to notify the client that the "server_max_window_bits" value that it proposed has been accepted, which is used by the client's inflater.
> 
> There's a known, open issue with the windowBits value 8, for reasons beyond the scope here. The deflater in zlib works around this by setting windowBits to 9, whenever the requested value is 8. Such a hack may work in the case of zlib streams where the size of the LZ77 window is encoded along with compressed data. It is possible for the inflater to read this value and adjust it's window size. However, this is not possible with raw deflate streams.
> So, zlib has been patched to return a failure if a window size of -8 were used. The failing function is deflateInit2().
> 
> To work around this zlib limitation, we need to make sure we don't entertain "server_max_window_bits=8". If this is received in a negotiation offer, we set the window size of the deflater to 9 and return "server_max_window_bits=9" in the negotiation response.
> 
> Details of the zlib limitation are here: [madler/zlib#171](https://github.com/madler/zlib/issues/171)

Commit: https://github.com/IBM-Swift/Kitura-WebSocket-NIO/pull/26/commits/c9d9b44d56de7c398a526b34dacf7b4302045f73

**Comment by pushkarnk** [comment]
> > One part of this memory leak is the `WebSocketConnection <----> ChannelHandlerContext` retain cycle. Another part, the more serious one, is a bug in #26 which ends up initialising a z_stream for every message (even when context takeover is configured, ideally it should've been initialised once per connection) but frees it only once (because context takeover is configured). Fixing this bug breaks the autobahn tests. We're unable to use context for compressing outgoing messages. I'm on this now.
> 
> The more serious memory leak issue is with context takeover, when we persist the z_streams created for the deflater and the inflater for the lifetime of a connection. They must be cleaned up while the connection is being closed.

Commit: https://github.com/IBM-Swift/Kitura-WebSocket-NIO/pull/26/commits/e9d717d56b560ff4739309aaaa0820a3e2f3af0f

**Comment by pushkarnk** [comment]
Fixed the other memory leak: https://github.com/IBM-Swift/Kitura-WebSocket-NIO/pull/33

**Comment by pushkarnk** [comment]
Fixes available in release 2.1.0
