### ISSUE TITLE
Porting fix of issue#60 on Kitura-WebSocket

### ISSUE THREAD

**Issue by pushkarnk** [IBM-Swift/Kitura-WebSocket-NIO#42]
It needs to be checked if [this issue](https://github.com/IBM-Swift/Kitura-WebSocket/issues/60) exists here and port the fix if it does.

**Comment by harish1992** [comment]
I followed similar approach  to check if this issue affects Kitura-WebSocket-NIO i.e,

 - Created a web socket Client using StarScream
 - Killed the client process

Following are my observations:

- WebSocket service was notified about this disconnect.
- Proper reason code wasrecieved ( i.e `noReasonCodeSent` in this case ).

My initial investigation shows issue https://github.com/IBM-Swift/Kitura-WebSocket/issues/60 does not exists in Kitura-WebSocket-NIO.

**Comment by pushkarnk** [comment]
Thanks @harish1992 Closing this issue.
