### ISSUE TITLE
cannot compile using latest version 2.1.1

### ISSUE THREAD

**Issue by ormaa** [IBM-Swift/Kitura-WebSocket-NIO#49]
I cannot compile if I try to use latest NIO package 2.1.1 and swift 5

I obtain this error : 
error: multiple products named 'KituraNet' in: Kitura-NIO, Kitura-net
error: multiple targets named 'KituraNet' in: Kitura-NIO, Kitura-net
error: multiple targets named 'KituraNetTests' in: Kitura-NIO, Kitura-net

this is my package : 

// swift-tools-version:5.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "test",
    dependencies: [
        .package(url: "https://github.com/IBM-Swift/Kitura", from: "2.6.0"),
        .package(url: "https://github.com/IBM-Swift/HeliumLogger.git", .upToNextMajor(from: "1.0.0")),
        .package(url: "https://github.com/IBM-Swift/Kitura-CouchDB.git", .upToNextMajor(from: "3.0.0")),
        .package(url: "https://github.com/IBM-Swift/SwiftKueryMySQL.git", from: "2.0.2"),
        .package(url: "https://github.com/IBM-Swift/Kitura-WebSocket-NIO.git", from: "2.1.1")
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "test",
            dependencies: ["Kitura", "HeliumLogger", "CouchDB", "SwiftKueryMySQL", "Kitura-WebSocket"]),
        .testTarget(
            name: "testTests",
            dependencies: ["test"]),
    ]
)

**Comment by pushkarnk** [comment]
@ormaa Kitura, by default, uses [Kitura-net](https://github.com/IBM-Swift/Kitura-net) for networking. [Kitura-NIO](https://github.com/IBM-Swift/Kitura-NIO) is a SwiftNIO based implementation of the same `KituraNet` API. 

In your case, while `Kitura-WebSocket-NIO` dependent on `Kitura-NIO`, `Kitura` is dependent on `Kitura-net`. 

In other words, `Kitura-WebSocket-NIO` is only compatible with Kitura running in the NIO mode. 
You'd need to set the env variable `KITURA_NIO=1` for that.

**Comment by pushkarnk** [comment]
@ormaa Did you get a chance to test with `KITURA_NIO=1`?

**Comment by ormaa** [comment]
Sorry, not yet as i am travelling for few days .
  
I will test just when i will be back
  
Thanks
  

  
  

  
  
>

**Comment by harish1992** [comment]
@ormaa  any update on this?

**Comment by ormaa** [comment]
No on my side
  

  
  

  
  
>

**Comment by pushkarnk** [comment]
> @ormaa Kitura, by default, uses [Kitura-net](https://github.com/IBM-Swift/Kitura-net) for networking. [Kitura-NIO](https://github.com/IBM-Swift/Kitura-NIO) is a SwiftNIO based implementation of the same `KituraNet` API.
> 
> In your case, `Kitura-WebSocket-NIO` is dependent on `Kitura-NIO`. On the other hand`Kitura` is dependent on `Kitura-net`. Hence the clash.
> 
> In other words, `Kitura-WebSocket-NIO` is only compatible with Kitura running in the NIO mode.
> You'd need to set the env variable `KITURA_NIO=1` for that.

@ormaa We're closing this issue with the suggestion quoted above. If you continue to face the problem, feel free to reopen/open a new issue. You could also get in touch with us over Slack. Thank you.
