### ISSUE TITLE
Cannot not connect to socket (iOS)

### ISSUE THREAD

**Issue by makleso6** [IBM-Swift/Kitura-WebSocket-NIO#50]
Hi! Thanks for awesome library.
I trying to run local web server on iOS and connect with WebSocket. But websocket can not connect with error ```Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}```

**Comment by pushkarnk** [comment]
@makleso6 Thanks for reporting. We need more information to get started with the investigation. Do you have a small program / sample code which will help us reproduce the issue?

**Comment by makleso6** [comment]
https://drive.google.com/open?id=1GsysPg5WugwL32PSDckebLuZ9ccxQ8fj Here iOS project, but I get another error (Starscream.WSError(type: Starscream.ErrorType.upgradeError, message: "Invalid HTTP upgrade", code: 404))
with Kitura w/o NIO it works fine

**Comment by harish1992** [comment]
Hi @makleso6 can you try registering the service path i.e `WebSocket.register` before `server.listen`. 
And also the argument to `SocketContainer` which is  
`Starscream.WebSocket.init(url: URL(string: "ws://127.0.0.1:\(port)/\(path)/")!))` has to be
`Starscream.WebSocket.init(url: URL(string: "ws://127.0.0.1:\(port)/\(path)")!))` or else server returns error 400.

**Comment by harish1992** [comment]
Hi @makleso6 , did the solution work?

**Comment by makleso6** [comment]
Hi @harish1992, Well, it seems to be working!
